name: app_de_libros
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter_svg: ^1.1.6
  flutter:
    sdk: flutter
  firebase_core: ^2.3.0
  firebase_database: ^10.0.6
  firebase_auth: ^4.1.4
  cloud_firestore: ^4.1.0
  flutter_login: ^4.1.0
  firebase_messaging: ^14.1.2
  firebase_performance_platform_interface: ^0.1.1+26
  firebase_analytics: ^10.0.6
  cupertino_icons: ^1.0.2
  image_picker: ^0.8.6  
  flutterfire_cli: ^0.2.7
  http: ^0.13.5
  html_unescape: ^2.0.0
  material_color_generator: ^1.1.0

  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Garamond
      fonts:
        - asset: fonts/Garamond.ttf
  assets:
    - images/

 #    - family: Schyler
 #      fonts:
 #        - asset: fonts/Schyler-Regular.ttf
 #        - asset: fonts/Schyler-Italic.ttf
 #          style: italic
 #    - family: Trajan Pro
 #      fonts:
 #        - asset: fonts/TrajanPro.ttf
 #        - asset: fonts/TrajanPro_Bold.ttf
 #          weight: 700
